# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='independiente',
            name='foto',
            field=models.TextField(max_length=1000),
        ),
    ]
