# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0002_auto_20160215_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='independiente',
            name='correoElectronico',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='independiente',
            name='foto',
            field=models.TextField(),
        ),
    ]
